const recipes = [

  {
    id: 10,
    title: "Chicken Breasts & spicy Honey Orange Glaze",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/Chicken Breasts with Spicy Honey Orange Glaze.webp",
    
    method: ["In small bowl, combine honey with juice concentrate, orange zest, garlic, salt and red pepper flakes.","Rinse chicken with cold water and pat dry. Season lightly with salt.", "In large non-stick skillet, heat margarine and oil over medium-high heat. Add chicken and cook about 4 minutes, until seared.",
      "Turn chicken, cook another 4 minutes until just cooked through.","Pour honey mixture over chicken and cook, turning chicken to coat as sauce begins to thicken, about 2 min.","Serve chicken breasts with honey-orange glaze spooned over the top."
    ],
    ingredients: [],
    category: "Dinner",
    diet: null,
    meat: "Chicken",
    trending: false,
    holiday: null,
    season: "summer",
    rating: 3.9,
    servings: 4,
  },
  {
    id: 11,
    title: "Chicken Lazone",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/Chicken Lazone.webp",
    method: ["Combine the seasonings and coat chicken breasts.","In large saute pan melt half of the butter and cook chicken over medium heat for about 7 to 8 minutes, turning once.","Pour the cream into the skillet and lower the heat.",
      "Simmer for several minutes, stirring until the sauce thickens then add the remaining butter.","When butter is melted place chicken breasts on four plates and top with the sauce."
    ],
    ingredients: ["1 teaspoon salt, 1 <sup> teaspoons chili powder,"],
    category: "Dinner",
    diet: null,
    meat: "Chicken",
    trending: false,
    holiday: null,
    season: "summer",
    rating: 3.9,
    servings: 5,
  },
  {
    id: 12,
    title: "Lemon Chicken",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/Lemon Chicken.webp",
    method: ["Combine first 3 ingredients in a large zip-lock bag. Add chicken, and seal bag. Marinate for 15 minutes in the refrigerator.","Combine eggs, 1/4 cup cornstarch, and baking powder in a large bowl; stir well. Dip chicken into batter, coating well.","Pour 2 cups oil into a large heavy skillet. Fry chicken in hot oil over medium-high heat until golden, turning occasionally. Drain on paper towels. Cut chicken into 1 1/2 inch X 1 inch pieces. Arrange on a serving platter.",
      "Combine chicken broth and next 4 ingredients; set aside. Place 2 tbsp oil in a large non-stick skillet; place over medium-high heat until hot. Add lemon slices, and stir fry 30 seconds. Add broth mixture, and stir fry 3 additional minutes or until sauce is thickened and clear. Pour over chicken. Serve immediately."
    ],
    ingredients: ["1 tablespoon dry sherry", "1 tablespoon soy sauce", "Lettuce", "Tomato", "Avocado"],
    category: "Dinner",
    diet: null,
    meat: "Chicken",
    trending: false,
    holiday: null,
    season: "summer",
    rating: 3.9,
    servings: 2,
  },
  
  {
    id: 13,
    title: "Peach oatmeal",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/BF-Peach oatmeal.jpg",
    method: [],
    ingredients: ["Shrimp", "Taco Shells", "Lettuce", "Tomato", "Avocado"],
    category: "Breakfast",
    diet: "vegan",
    meat: null,
    trending: false,
    holiday: null,
    season: "summer",
    rating: 3.9,
    servings: 3,
  },
  {
    id: 14,
    title: "Pasteles De Guayaba",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/BF-Pasteles De Guayaba.jpg",
    ingredients: ["Shrimp", "Taco Shells", "Lettuce", "Tomato", "Avocado"],
    method: [],
    category: "Breakfast",
    diet: "vegan",
    meat: null,
    trending: false,
    holiday: null,
    season: "summer",
    rating: 3.9,
    servings: 2,
  },
  {
    id: 15,
    title: "Egg Rolls",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/BF-Breakfast Egg Rolls.jpg",
    ingredients: ["Shrimp", "Taco Shells", "Lettuce", "Tomato", "Avocado"],
    method: [],
    category: "Breakfast",
    diet: "vegan",
    meat: null,
    trending: false,
    holiday: null,
    season: "summer",
    rating: 3.9,
    servings: 1,
  },
  {
    id: 16,
    title: "Cilantro Chicken",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/Cilantro Chicken.webp",
    ingredients: ["Shrimp", "Taco Shells", "Lettuce", "Tomato", "Avocado"],
    method: [],
    category: "Dinner",
    diet: null,
    meat:"Chicken",
    trending: false,
    holiday: null,
    season: "summer",
    rating: 3.9,
    servings: 2,
  },
  
  {
    id: 17,
    title: "Instant Pot Cocktail Meatballs",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/(Christmas) Instant pot cocktail meatballs.jpg",
    ingredients: ["Shrimp", "Taco Shells", "Lettuce", "Tomato", "Avocado"],
    method: [],
    category: "Breakfast",
    diet: null,
    meat: null,
    trending: false,
    holiday: "christmas",
    season: "summer",
    rating: 3.9,
    servings: 8,
  },
  
  {
    id: 18,
    title: "Cheesecake cookies",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/Chrismas(Cheesecake cookies).jpg",
    ingredients: ["Shrimp", "Taco Shells", "Lettuce", "Tomato", "Avocado"],
    method: [],
    category: "Breakfast",
    diet: null,
    meat: null,
    trending: false,
    holiday: "christmas",
    season: "summer",
    rating: 3.9,
    servings: 5,
  },
  
  {
    id: 19,
    title: "Instant Pot Cocktail Meatballs",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/(Christmas) Instant pot cocktail meatballs.jpg",
    ingredients: ["Shrimp", "Taco Shells", "Lettuce", "Tomato", "Avocado"],
    method: [],
    category: "Breakfast",
    diet: null,
    meat: null,
    trending: false,
    holiday: "christmas",
    season: "summer",
    rating: 3.9,
    servings: 10,
  },
  {
    id: 20,
    title: "Creamy vegan pesto pasta with broccoli",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/Vegan- Creamy vegan pesto pasta with broccoli.jpg",
    ingredients: ["Shrimp", "Taco Shells", "Lettuce", "Tomato", "Avocado"],
    method: [],
    category: null,
    diet: "vegan",
    meat: null,
    trending: false,
    holiday: null,
    season: "summer",
    rating: 3.9,
    servings: 4,
  },
  {
    id: 21,
    title: "Instant Pot Cocktail Meatballs",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/Vegan-Easy Black Beans & Rice.webp",
    ingredients: ["Shrimp", "Taco Shells", "Lettuce", "Tomato", "Avocado"],
    method: [],
    category: null,
    diet: "vegan",
    meat: null,
    trending: false,
    holiday: "christmas",
    season: "summer",
    rating: 3.9,
  },
  {
    id: 22,
    title: "Instant Pot Cocktail Meatballs",
    // description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/(Christmas) Instant pot cocktail meatballs.jpg",
    ingredients: ["Shrimp", "Taco Shells", "Lettuce", "Tomato", "Avocado"],
    method: [],
    category: "Breakfast",
    diet: null,
    meat: null,
    trending: false,
    holiday: "christmas",
    season: "summer",
    rating: 3.9,
    servings: 3,
  },
  

];

export default recipes;

