const recipes = [
  {
    id: 1,
    title: "Beef Braised Lamb Shanks",
    description: "A classic Italian pasta.",
    image: "/images/Beef Braised Lamb Shanks.jpg",
    ingredients: ["Eggs", "Pancetta", "Black Pepper"],
    method: [],
  },
  {
    id: 2,
    title: "Beef Lasagna",
    description: "A flavorful Italian lasagna with beef and cheese.",
    image: "/images/Beef Lasagna Recipe.jpg",
    ingredients: ["Ground Beef", "Lasagna Noodles", "Tomato Sauce", "Cheese", "Spices"],
    method: [],
  },
  {
    id: 3,
    title: "Roasted Potato Salad with Broccoli",
    description: "A healthy and tasty roasted potato salad with broccoli.",
    image: "/images/Roasted Potato Salad with broccoli.jpg",
    ingredients: ["Potatoes", "Broccoli", "Olive Oil", "Garlic", "Salt"],
    method: [],
  },
  {
    id: 4,
    title: "Mutton Stew and Dumplings",
    description: "A hearty mutton stew with soft dumplings.",
    image: "/images/Mutton Stew and Dumplings.jpg",
    ingredients: ["Mutton", "Flour", "Spices", "Garlic", "Vegetables"],
    method: [],
  },
  {
    id: 5,
    title: "Chakalaka Pork Shank",
    description: "A flavorful South African dish of pork shank with chakalaka.",
    image: "/images/Chakalaka Pork Shank.jpg",
    ingredients: ["Pork Shank", "Chakalaka", "Tomato Sauce", "Spices", "Garlic"],
    method: [],
  },
  {
    id: 6,
    title: "Chicken Mayo Sandwitch",
    description: "A classic Indian chicken curry with aromatic spices.",
    image: "/images/Chicken Mayo Sandwitch.jpg",
    ingredients: ["Chicken", "Yogurt", "Tomato Sauce", "Curry Powder", "Ginger"],
    method: [],
  },
  {
    id: 7,
    title: "One pot mince & cheesy pasta",
    description: "A comforting beef stew with vegetables and a rich gravy.",
    image: "/images/One pot mince & cheesy pasta.jpg",
    ingredients: ["Beef", "Carrots", "Potatoes", "Onion", "Beef Broth"],
    method: [],
  },
  {
    id: 8,
    title: "Savoury Waffle Chicken Burger",
    description: "A healthy vegetable stir fry with soy sauce and garlic.",
    image: "/images/Savoury Waffle Chicken Burger.jpg",
    ingredients: ["Bell Peppers", "Broccoli", "Soy Sauce", "Garlic", "Ginger"],
    method: [],
  },
  {
    id: 9,
    title: "Apple + Hummus Combo",
    description: "Spicy shrimp tacos with fresh toppings and a tangy sauce.",
    image: "/images/Apple + Hummus Combo.jpg",
    ingredients: ["Shrimp", "Taco Shells", "Lettuce", "Tomato", "Avocado"],
    method: [],
  }
];

export default recipes;
